name: Check that the license in the root folder is up to date

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-license:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: tibdex/github-app-token@v2.1
        id: get_installation_token
        with:
          app_id: 384283
          private_key: ${{ secrets.CHECKOUT_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.get_installation_token.outputs.token }}

      - name: Check the license
        run: |
          diff --no-dereference License LICENSES/LicenseRef-TridentMSLA.txt
